steps:
    - name: SSH and Run update.sh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GCP_HOST }}
        username: ${{ secrets.GCP_USERNAME }}
        key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
        script: |
          cd ~/GCP-4/personal-portfolio
          ./update.sh